# Generated by Django 2.2.4 on 2019-08-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190819_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='gallery_image',
            field=models.FileField(upload_to=''),
        ),
    ]
